# Assignment - 2 Solution
##### Author : Sudesh Chaudhary

In [1]:
import pandas as pd
import numpy as np

In [2]:
def solve(I,v,w,t):
    hi = np.dot(I,v)
    print("hidden layer activaton")
    print(hi)
    # log-sigmoid transfer function
    oh1 = 1.0/(1.0+np.exp(-hi))
    print("hidden layer output")
    print(oh1)
    
    io1 = np.dot(oh1,w)
    print("activation for output layer")
    print(io1)
    # tan-sigmoid transfer function
    o1 = (np.exp(io1)-np.exp(-io1))/(np.exp(io1)+np.exp(-io1))
    print("output")
    print(o1)
    
    delta_w = np.zeros((3,2))
    for j in range(3):
        for k in range(2):
            sum =(t[k]-o1[k])*(1-o1[k])*(1+o1[k])*(oh1[j])
            delta_w[j][k]=sum
    print("delta w ")
    print(delta_w)
    delta_v = np.zeros((2,3))
    
    for i in range(2):
        for j in range(3):
            sum=0
            for k in range(2):
                x = (t[k]-o1[k])*(1-o1[k])*(1+o1[k])
                x*= w[j][k]
                x*=oh1[j]*(1-oh1[j])
                x*=I[i]
                sum+=x
            delta_v[i][j]=sum
    print("delta v")
    print(delta_v)
    return [delta_w,delta_v]

In [3]:
# inputs
i1 = np.array([0.6,0.4])
i2 = np.array([0.3,0.7])

In [4]:
# weight matrix between input and hidden layer 
v = np.array([[0.2,0.4,0.3],[0.1,0.6,0.5]])

In [5]:
# weight matrix between hidden and output layer
w = np.array([[0.1,0.2],[0.2,0.3],[-0.1,0.4]])

In [6]:
# outputs
t1 = np.array([0.2,0.4])
t2 = np.array([0.5,0.1])

In [7]:
# Iteration 1
output1 = solve(i1,v,w,t1) # [delta w, delta v]
output2 = solve(i2,v,w,t2)
# output1
# print(output1[0],output2[0])

hidden layer activaton
[0.16 0.48 0.38]
hidden layer output
[0.53991488 0.61774787 0.5938731 ]
activation for output layer
[0.11815375 0.53085658]
output
[0.11760699 0.48603559]
delta w 
[[ 0.04386992 -0.03547854]
 [ 0.05019412 -0.04059305]
 [ 0.04825421 -0.03902421]]
delta v
[[-0.00074774 -0.0004906  -0.00497955]
 [-0.0004985  -0.00032707 -0.0033197 ]]
hidden layer activaton
[0.13 0.54 0.44]
hidden layer output
[0.53245431 0.63181242 0.60825903]
activation for output layer
[0.11878201 0.5393382 ]
output
[0.11822651 0.49248684]
delta w 
[[ 0.20043564 -0.1582943 ]
 [ 0.23783773 -0.18783265]
 [ 0.22897136 -0.18083042]]
delta v
[[-0.0016292  -0.00097005 -0.01119157]
 [-0.00380148 -0.00226346 -0.02611365]]


In [8]:
# calculating delta_w
delta_w = 0.15*(output1[0]+output2[0])
delta_w

array([[ 0.03664583, -0.02906592],
       [ 0.04320478, -0.03426385],
       [ 0.04158384, -0.03297819]])

In [9]:
# calculating delta_v
delta_v = (0.3*(output1[1]+output2[1]))/4
delta_v

array([[-0.00017827, -0.00010955, -0.00121283],
       [-0.0003225 , -0.00019429, -0.0022075 ]])

In [10]:
# updating weight matrices
w = w+delta_w
v = v+delta_v
print(w)
print(v)

[[ 0.13664583  0.17093408]
 [ 0.24320478  0.26573615]
 [-0.05841616  0.36702181]]
[[0.19982173 0.39989045 0.29878717]
 [0.0996775  0.59980571 0.4977925 ]]


In [11]:
# Iteration 2
output21 = solve(i1,v,w,t1) # [delta w, delta v]
output22 = solve(i2,v,w,t2)

hidden layer activaton
[0.15976404 0.47985655 0.3783893 ]
hidden layer output
[0.53985627 0.617714   0.59348456]
activation for output layer
[0.18933101 0.47425055]
output
[0.18710072 0.44162727]
delta w 
[[ 0.00671998 -0.01808978]
 [ 0.00768913 -0.02069868]
 [ 0.00738753 -0.01988678]]
delta v
[[-0.00060018 -0.0008327  -0.00188552]
 [-0.00040012 -0.00055513 -0.00125702]]
hidden layer activaton
[0.12972077 0.53983113 0.4380909 ]
hidden layer output
[0.53238479 0.63177313 0.60780404]
activation for output layer
[0.19089283 0.48196499]
output
[0.18860742 0.44781593]
delta w 
[[ 0.1598834  -0.1480377 ]
 [ 0.18973126 -0.17567414]
 [ 0.18253297 -0.16900917]]
delta v
[[-4.85004015e-04 -5.95888554e-05 -8.55296178e-03]
 [-1.13167604e-03 -1.39040663e-04 -1.99569108e-02]]


In [12]:
delta_2w = 0.15*(output1[0]+output2[0]) + 0.2*(delta_w) # momentum term = alpha x delta_w_prev
delta_2w

array([[ 0.043975  , -0.03487911],
       [ 0.05184573, -0.04111663],
       [ 0.0499006 , -0.03957383]])

In [13]:
delta_2v = (0.3*(output1[1]+output2[1]))/4 +0.2*(delta_v)
delta_2v

array([[-0.00021393, -0.00013146, -0.0014554 ],
       [-0.000387  , -0.00023315, -0.002649  ]])

In [14]:
w = w+delta_2w
w

array([[ 0.18062083,  0.13605497],
       [ 0.29505051,  0.22461952],
       [-0.00851556,  0.32744797]])

In [15]:
v = v+delta_2v
v

array([[0.1996078 , 0.39975899, 0.29733177],
       [0.0992905 , 0.59957256, 0.4951435 ]])